<?php
/**
 * @file
 * Telemundo Deportes login customizations
 *
 * This module is intended to disable the public login urls and
 * replace them with private login urls.
 */

/**
 * Implements hook_menu.
 *
 * Private login page for development
 * and other backend users.
 */
function dezzys_login_menu() {
  $items = array();
  $items['des'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_login'),
    'access callback' => 'user_is_anonymous',
  );
  return $items;
}

/**
 * Implements hook_menu_alter.
 *
 * Disable drupal default public login page
 * for anonymous and robot users.
 */
function dezzys_login_menu_alter(&$items) {
  $items['user']['access callback'] = 'user_is_logged_in';
  $items['user/login']['access callback'] = 'user_is_logged_in';
  $items['user/register']['access callback'] = 'user_is_logged_in';
  $items['user/password']['access callback'] = 'user_is_logged_in';
}
